[BE] 폴더를 조회한다.
woowa-techcamp-2024/Team6-Drive pull request #10
Opened 2024-08-13 04:52 UTC by i960107

- resolves #5 

---

### 🚀 어떤 기능을 구현했나요 ?
- 폴더 조회시 폴더에 속한 폴더와 파일 리스트를 응답한다.
  - 권한이 있는(자신이 생성한)폴더만 조회 가능하다. 아니면 403 Forbidden을 응답한다.
  - 폴더 우선 조회.
  - cursorId(폴더나 파일의 PK)와 cursorType(Folder, File)을 지정할 수 있다.
  - 정렬 조건을 생성날짜나 사이즈로 지정할 수 있다.
  - 없는 페이지 조회시 빈 페이지를 반환한다.
- 폴더 조회를 테스트한다.
### 🔥 어떻게 해결했나요 ?
1. Pageable 방식과 Cursor방식(No-offset) 중에 Cursor방식을 선택
  + pageable은 내부적으로 limit과 offset을 사용하는데 폴더 테이블과 파일 테이블의 조회 결과를 조인해서 한번에 페이지 결과로 생성하는 것이 복잡하고 한번에 로직 파악하기 어려움.
   + 일반적으로 offset방식은 버리지만 읽어야하는 행의 개수가 많아져서 뒤 페이지 조회시 속도가 느리지만, `parentFolderId` 인덱스로 필터링한 결과에 대해서 페이징하기 때문에 성능 이슈 없음.
  + Cursor방식은 CursorType과 CursorId를 사용해서 조회.   
    + 처음 조회시 `CursorType` 은 Folder, `CursorId` 는 1로 요청 필요.  
    + 폴더 조회 응답에 다음 조회시 사용할`nextCursorType`, `nextCursorId`를 함께 전달한다. 
2. 조회 속도를 높이기 위해 FileMetadata, FolderMetadata의 `parentFolderId` 필드에 인덱스를 추가한다.
3. Controller에서 CursorType과 FolderContentsSortField는 enum으로 받아서 특정한 값만 허용하도록 한다. 허용되지 않는 값 전달시 BadRequest 발생

### 📝 어떤 부분에 집중해서 리뷰해야 할까요?
- 적절한 인덱스가 설정되었나
- 서비스 로직이 적절한가

### 📚 참고 자료, 할 말

2024-08-13 05:52 UTC, kariskan requested changes
수고하셨습니다.

2024-08-13 05:52 UTC, kariskan commented on src/main/java/com/woowacamp/storage/domain/folder/dto/CursorType.java
> +		for (CursorType field : CursorType.values()) {
```
return Arrays.stream(values())
         .filter(cursorType -> cursorType.getValue().equalsIgnoreCase(value))
         .findFirst()
         .orElseThrow(() -> ErrorCode.~~);
```
하면 좋을 것 같습니다.

2024-08-13 05:52 UTC, kariskan commented on src/main/java/com/woowacamp/storage/domain/folder/controller/FolderController.java
> +	public FolderContentsDto getFolderContents(@PathVariable Long folderId, @RequestParam Long userId,
파라미터가 너무 많은데 @ModelAttribute를 사용하는건 어떨까요

2024-08-13 05:52 UTC, kariskan commented on src/main/java/com/woowacamp/storage/domain/folder/service/FolderService.java
> +		CursorInfo nextCursor = determineNextCursor(folders, files, size);
이게 왜 필요한걸까요? 클라이언트 입장에서는 커서 기반 페이징에서 그냥 마지막 데이터에 대한 정보를 넘기면 그 정보(커서) 뒤에 요소들만 조회해 올텐데요

2024-08-13 05:54 UTC, seungh1024 requested changes
수고하셨습니다.

전체적으로 간단하게 주석을 추가하면 좋을 것 같아요.
테스트 코드도 @DisplayName이나 @Nested로 구분하면 어떤 테스트인지 이해하기 쉬울 것 같습니다.

2024-08-13 05:54 UTC, seungh1024 commented on src/main/java/com/woowacamp/storage/domain/file/repository/FileMetadataRepository.java
> +	List<FileMetadata> findByParentFolderIdAndIdGreaterThanAndUploadStatus(Long folderId, Long cursorId,
개인적으로 메소드 이름이 너무 길어서 이해가 힘듭니다.
네이티브 쿼리를 사용하거나 MyBatis를 사용하는 것이 좋아 보여요.

추가로 PageRequest를 사용하는 것은 기본적으로 offset 기반 페이징에서 사용한다고 합니다. 해당 코드에서는 커서 기반 페이징을 구현하기 위해 억지로 사용한 것 같습니다.

@Query()나 MyBatis를 사용해보심이 어떨까요?

2024-08-13 05:54 UTC, seungh1024 commented on src/main/java/com/woowacamp/storage/domain/folder/controller/FolderController.java
> +		@RequestParam Long cursorId, @RequestParam CursorType cursorType, @RequestParam(defaultValue = "100") int size,
size 필드에 대한 검증이 필요할 것 같아요.(최대 값 제한이라던지..)

2024-08-13 05:54 UTC, seungh1024 commented on src/main/java/com/woowacamp/storage/domain/folder/dto/CursorType.java
> +	CursorType(String value) {
@AllArgsConstructor로 변경하면 좋을 것 같아요.

2024-08-13 05:54 UTC, seungh1024 commented on src/main/java/com/woowacamp/storage/domain/folder/dto/CursorType.java
> +		throw new IllegalArgumentException("Invalid sort field: " + value);
CustomException으로 변경해주시면 좋을 것 같아요.

2024-08-13 05:54 UTC, seungh1024 commented on src/main/java/com/woowacamp/storage/domain/folder/dto/FolderContentsSortField.java
> +		throw new IllegalArgumentException("Invalid sort field: " + value);
CustomException으로 바꿔주세요!

2024-08-13 05:54 UTC, seungh1024 commented on src/main/java/com/woowacamp/storage/domain/folder/dto/FolderContentsSortField.java
> +	FolderContentsSortField(String value) {
@AllArgsConstructor 사용하면 좋을 것 같습니다.

2024-08-13 05:54 UTC, seungh1024 commented on src/main/java/com/woowacamp/storage/domain/folder/repository/FolderMetadataRepository.java
> +	List<FolderMetadata> findByParentFolderIdAndIdGreaterThan(Long folderId, Long cursorId, PageRequest of);
위와 같은 이유로 변경했으면 좋겠습니다. 이해하기가 힘든 것 같아요.

2024-08-13 23:21 UTC, i960107 commented on src/main/java/com/woowacamp/storage/domain/folder/dto/FolderContentsSortField.java
> +		throw new IllegalArgumentException("Invalid sort field: " + value);
수정했습니다~

2024-08-13 23:21 UTC, i960107 commented on src/main/java/com/woowacamp/storage/domain/folder/dto/CursorType.java
> +		throw new IllegalArgumentException("Invalid sort field: " + value);
수정했습니다~

2024-08-13 23:21 UTC, i960107 commented on src/main/java/com/woowacamp/storage/domain/folder/dto/FolderContentsSortField.java
> +	FolderContentsSortField(String value) {
@AllArgsConstructor의 경우 같은 타입의 필드가 있으면 생성자 파라미터 순서가 바뀌어도 동작하기 때문에 지양하는 것이 좋다고 생각합니다.😀 이 클래스는 필드가 하나이고 수정될 가능성이 적다고 생각해서 일단 고쳐두었습니다.

2024-08-13 23:21 UTC, i960107 commented on src/main/java/com/woowacamp/storage/domain/folder/dto/CursorType.java
> +	CursorType(String value) {
@AllArgsConstructor의 경우 같은 타입의 필드가 있으면 생성자 파라미터 순서가 바뀌어도 동작하기 때문에 지양하는 것이 좋다고 생각합니다.😀 이 클래스는 필드가 하나이고 수정될 가능성이 적다고 생각해서 일단 고쳐두었습니다.

2024-08-13 23:25 UTC, i960107 commented on src/main/java/com/woowacamp/storage/domain/folder/controller/FolderController.java
> +		@RequestParam Long cursorId, @RequestParam CursorType cursorType, @RequestParam(defaultValue = "100") int size,
size값을 매우 크게 요청하면 반환해야할 데이터가 커져서 서버 부하 문제가 발생할 수 있겠네요 size max = 1000으로 수정했습니다~

2024-08-13 23:27 UTC, i960107 commented on src/main/java/com/woowacamp/storage/domain/folder/service/FolderService.java
> +		CursorInfo nextCursor = determineNextCursor(folders, files, size);
그렇네요! CursorInfo는 반환하지 않고 클라이언트측에 마지막 데이터를 기준으로 요청하도록 수정하였습니다~

2024-08-13 23:28 UTC, i960107 commented on src/main/java/com/woowacamp/storage/domain/folder/controller/FolderController.java
> +	public FolderContentsDto getFolderContents(@PathVariable Long folderId, @RequestParam Long userId,
Dto 따로 만들고 ModelAttribute로 처리했습니다. Dto내에서 validation하고 default 값 넣어주도록 수정했습니다

2024-08-13 23:32 UTC, i960107 commented on src/main/java/com/woowacamp/storage/domain/folder/dto/CursorType.java
> +		for (CursorType field : CursorType.values()) {
가독성이나 외부 변수를 수정해서 사이드 이펙트가 발생하는 것을 방지하기 위해서 for문보다 stream을 사용하는 것이 좋군요! 수정하였습니다😀

2024-08-14 00:46 UTC, kariskan commented on src/main/java/com/woowacamp/storage/domain/folder/dto/GetFolderContentsRequestParams.java
> +	@Positive Long userId,
Positive는 not null에 대한 검증이 안됩니다.

2024-08-14 06:34 UTC, i960107 commented on src/main/java/com/woowacamp/storage/domain/folder/dto/GetFolderContentsRequestParams.java
> +	@Positive Long userId,
추가했습니다~

2024-08-15 11:57 UTC, seungh1024 requested changes
수고하셨습니다!

2024-08-15 11:57 UTC, seungh1024 commented on src/main/java/com/woowacamp/storage/domain/folder/controller/FolderController.java
> +		@Valid @ModelAttribute GetFolderContentsRequestParams request) {
혹시 @PathVariable과 @ModelAttribute로 요청 데이터를 따로 처리하는 이유가 있을까요?

2024-08-15 12:18 UTC, kariskan requested changes
확인해주세요~

2024-08-15 12:18 UTC, kariskan commented on src/main/java/com/woowacamp/storage/domain/folder/repository/FolderCustomRepositoryImpl.java
> +						.or(folderMetadata.createdAt.eq(dateTime).and(folderMetadata.id.gt(cursorId)));
현재는 column1 >= cursorColumn1 or (column1 = cursorColumn1 and column2 > cursorColumn2) 이렇게 돼 있는데
column1 >= cursorColumn1 and (column1 = cursorColumn1 or column2 > cursorColumn2) 이렇게 하면 인덱스를 더 잘 탈 것 같습니다.

2024-08-15 12:18 UTC, kariskan commented on src/main/java/com/woowacamp/storage/domain/file/repository/FileCustomRepositoryImpl.java
> +	public List<FileMetadata> selectFilesWithPagination(long parentId, long cursorId,
요 쿼리도 폴더처럼 바꿔야 하는 것 아닌가요?

2024-08-15 14:17 UTC, KoKimSS commented on src/main/java/com/woowacamp/storage/domain/folder/repository/FolderCustomRepositoryImpl.java
> +						.or(folderMetadata.createdAt.eq(dateTime).and(folderMetadata.id.gt(cursorId)));
and 로 하면 column1 >= cursorColumn1 앞의 조건으로 검색한 결과가 (column1 = cursorColumn1 or column2 > cursorColumn2) 뒤의 검색결과로 인해 필터링 돼서 원하는 결과가 나오지 않을 것 같습니다 !

ex ) 100이상인 사이즈 중에서 결과를 찾고싶은데
size >= 100 and ( size = 100 or id > 1 )  : 100 이상인 것중에 100이 아닌것은 조건 결과에서 빠지게 됩니다 !

2024-08-15 14:17 UTC, KoKimSS commented on src/main/java/com/woowacamp/storage/domain/file/repository/FileCustomRepositoryImpl.java
> +	public List<FileMetadata> selectFilesWithPagination(long parentId, long cursorId,
수정해서 올리겠습니다 !

2024-08-15 14:21 UTC, kariskan commented on src/main/java/com/woowacamp/storage/domain/folder/repository/FolderCustomRepositoryImpl.java
> +						.or(folderMetadata.createdAt.eq(dateTime).and(folderMetadata.id.gt(cursorId)));
아 잘 못 말씀드렸네요.
column1 >= cursorColumn1 and (**column1 > cursorColumn1** or column2 > cursorColumn2)
이렇게 해야할 것 같습니다

2024-08-15 18:12 UTC, KoKimSS commented on src/main/java/com/woowacamp/storage/domain/folder/repository/FolderCustomRepositoryImpl.java
> +						.or(folderMetadata.createdAt.eq(dateTime).and(folderMetadata.id.gt(cursorId)));
size >= 100 and ( size > 100 or id > 1 ) 
이렇게 하면 size가 100인 경우는 조건에서 벗어나는 것 같습니다.

추가적으로 현재 쿼리에서 앞에 비교문에 >= 가 아닌 > 로 사용 되고 있습니다.
- size > 100 or ( size == 100 and id > 1) 이런식으로 사용되고 있습니다.

2024-08-15 18:34 UTC, KoKimSS commented on src/main/java/com/woowacamp/storage/domain/folder/repository/FolderCustomRepositoryImpl.java
> +						.or(folderMetadata.createdAt.eq(dateTime).and(folderMetadata.id.gt(cursorId)));
<img width="667" alt="스크린샷 2024-08-16 오전 3 21 41" src="https://github.com/user-attachments/assets/d978b108-98f7-407c-a862-c191e78054b5">

맞네요 참조 글에서 where 절에 or 조건을 사용하면 잘못된 인덱스를 탈 가능성이 있다고 하네요. 나중에 실행 계획도 확인해 봐야겠습니다.

2024-08-16 01:09 UTC, seungh1024 approved these changes

2024-08-16 01:59 UTC, kariskan approved these changes

2024-08-16 01:59 UTC, merged